#!/usr/bin/env bun
/**
 * Regenerate `wasm-blob.ts` — wasmoon's Lua 5.4 wasm, gzipped and base64'd
 * into a TS constant.
 *
 * Why embed it at all: wasmoon locates `glue.wasm` through emscripten's
 * `locateFile`, which bakes in the BUILD MACHINE's absolute node_modules path.
 * `bun build --compile` does not rewrite or embed it, so a shipped binary looks
 * for a directory that exists only on the machine that built it and dies with
 * ENOENT on first use. The failure is invisible in CI (the path is still there)
 * and only appears on a user's machine.
 *
 * The asset-import form (`import p from "wasmoon/dist/glue.wasm" with { type:
 * "file" }`) fixes a single-stage compile but NOT loop's build: core is bundled
 * to dist/index.js first, which emits the wasm as a sibling file, and the later
 * --compile of the CLI does not pick it up. Embedding the bytes in a module is
 * the only form that survives both stages.
 *
 * Run after bumping wasmoon:  bun packages/core/src/extensions/builtin/lua/scripts/generate-wasm.ts
 */
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const wasmPath = fileURLToPath(import.meta.resolve("wasmoon/dist/glue.wasm"));
const version = (
    JSON.parse(await Bun.file(fileURLToPath(import.meta.resolve("wasmoon/package.json"))).text()) as {
        version: string;
    }
).version;

const raw = new Uint8Array(await Bun.file(wasmPath).arrayBuffer());
const gz = Bun.gzipSync(raw);
const b64 = Buffer.from(gz).toString("base64");

const out = join(import.meta.dir, "..", "wasm-blob.ts");
await Bun.write(
    out,
    `// GENERATED by scripts/generate-wasm.ts — do not edit.
// wasmoon ${version} glue.wasm (Lua 5.4), gzipped then base64'd.
// raw ${raw.length} B -> gzip ${gz.length} B -> base64 ${b64.length} chars.
export const WASMOON_VERSION = ${JSON.stringify(version)};
export const GLUE_WASM_GZ_B64 =
    "${b64}";
`,
);
console.log(`wrote ${out}`);
console.log(`wasmoon ${version}: raw ${raw.length} -> gzip ${gz.length} -> b64 ${b64.length}`);
